### ISSUE TITLE
Make a decent NixOS base image

### ISSUE THREAD

**Issue by Xe** [Xe/waifud#6]
Something that you can throw around and assimilate to your needs with cloud-init.

**Comment by Xe** [comment]
I have an attempt now, requires user-data like this though:

```yaml
#cloud-config
#vim:syntax=yaml

users:
  - name: root
    shell: /run/current-system/sw/bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPg9gYKVglnO2HQodSJt4z4mNrUSUiyJQ7b+J798bwD9
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYr9hiLtDHgd6lZDgQMkJzvYeAXmePOrgFaWHAjJvNU
```
